server.error.whitelabel.enable=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.data.mongodb.uri=mongodb+srv://brenodario620_db_user:<db_password>@cluster0.o5dkuxi.mongodb.net/produtosdb?retryWrites=true&w=majority&appName=Cluster0
server.port=8080
